#############################
## Makefile - Jacob Adkins ##
#############################

CXX = gcc 

all : userspace

a.out : userspace.c
	${CXX} -Wall -std=c99 $^ -o $@

clean :
	\rm -f userspace 

###### End of Makefile ###### 
